# 服务器配置
server:
  port: 8080
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
    worker: 256
# sql输出日志
#logging:
#  level:
#    com.chunhui.dao: DEBUG
# 项目全局配置
project:
  name: whatsup-mall-plus # 项目名称
  #  fileUploadPath: /opt/whatsup-mall-plus/upload/   # 上传文件的默认url前缀，根据部署设置自行修改，linux下路径  E:\\upload\\
  fileUploadPath: E:\\upload\\          # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  orderUnpaidOverTime: 300 # 订单未支付超期时间，单位秒
  serverUrl: http://45.156.24.206:80 # 服务器地址

spring:
  #禁用Thymeleaf模板缓存
  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据源配置
  datasource:
    username: gh
    password: 123456
    url: jdbc:mysql://45.156.24.206:3306/newbee_mall_plus_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikariCP
      minimum-idle: 100
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #  redis
  redis:
    host: 45.156.24.206
    port: 6379
    password:
    timeout: 5000ms
    connect-timeout: 5000ms
    expire: 400
    client-type: lettuce
# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id: 2021000119608060
  rsa-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCDnr94H7bcZY9GsCI5kLVm9KtxMwFtCjE3i2nlJOmG4Bp4stGYVCREY7tgvpb7hcAFUGIBqP96hN4VlREBlN8c3Cwbz0jwqabI1n7slE6remHlOvOlMUDOMoaH2S+t9c32lM25KFlDSeL8wN3gsBoAy3CzEaFjjoOPf8MZTMzHzm5mllRqz8nvtbqcsea2iZncUyaje3kT4su8rlUyrA8150/Of2+/1LReFpWvCcemXg28sWtTZmoLz6pp/Chi2qtUiFWbCQZG+Q5Pegw0rOcE8mokG2ux+N/wKhB4kMvhdBTdfXNGjaBjMifVnFBhKv5wqj80R3yNIj5JMR2+4GefAgMBAAECggEAYfTY3UcFKfxv6JUXs64ORASeP85NJmDqhkM82axiHN5W9TNoqC0fHML45qSR67n8Ujgj6MZk9UNDod5iXMH2Vx1JupzH1Uz98wUoS1yJPDgF+bupL217pLqXwy0Rvi9tTTIr9bygymKIC8Jin2GQyLygMLVTXqvnH/pfMkolMiJN8hTFvRE4LfuTa4ZBzB2og2aLqZV+A7WyILdku/DS8hrDNlUjGknu77ecgycG1nwRv7viecH2QbsJTMZpEdz1Zj0Um8vG28t4my72Sms2HKji28LRrHITYvQL/IJBro/WjyNwmZPIJwHzMrSRVGqQOQAHDfb0Ce55UyOo3cx86QKBgQDSEHVow2Ck/EF0Op/Rnvlter3S4JgyU2hVtMFQlrTG27+dbC/tb8A4jENlt61pFxhItE9VOZz9mvFzJPDcODTirRHlaeAnWGxeET/Iha1fpGdQ6fAItY+wa27oCUiDhJqfK5USIWR9TlBqJfW0T/icQikNZU9mJBtAmN/8U7qxfQKBgQCgZu5JzzFEdQxl4R1NXDe0f3E2GHca42oc0DGOlnJeL8o7xqADzx3goZJgZsfCxggU7YXVWHKLKZnju+/NDK7o49RUwh+qpyKw6VV7KMCYbjNACtrpufW0/sePiPvB2Pcjz9MfwhS/aB0IgFi0Ykxwfdn+xBa2ikTpmWLKwbSISwKBgQCoD/TvYUkkFpIDfJe67RafyZCvc3Mw6FxUHa6AXGK7qrpuJ01dCIhgdY/ChKafqpOKL4A9Lj/1Ao7kUYzGk810AYWM5x0oPW1OATznoFOqbm0eZlvdi+0u93Ue/bZfSqsuZ373p3GvcwWRN1eR8F12HtSbXA+fJ4oKL4Ucapy2PQKBgAwQ8if3QBuIOpCHaK7jGwWm+Js7J+qL5PWZ68BwLNZM/geVH4Bp2jOFs/8wfCJ4xy7b109/Qc6aKItrHdTs+VNnoBdoKv2paQCp7NZA8IwG7jAJIQKoDIW7DMQNZ/LjIWQ+RAGFlg34BQcYsJOROXLU5Ms3cQX2TMzNzxK1k6EVAoGBAKplZVxqTPI79FPMVM0f8k7w/zVNc/WxfApbcNV6xYVaFXIqNo7gzs3rqdYGwKGWMaL43M7WaYsBM/YxB+8YKSbCPVbOSw2jq3ufQk5aHiDklkBqrGAFz3e9nIS6zS5SI71L7h8cFljIQleYkEG3vTm+IGf46386pBMiFBUKfS+H
  alipay-public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApDFGgJ7G1fzUbEAp5jMxcBuhRivbyESGP7We1EZXVTsul4c/Qv4tKflGC+0EdGmmh+X67RI2s4SgHDUo3JXvtj5Os9/sveGy8Dns4RinLXAQm5jU/QoPWa1A83zdH4g4urm2+mUU4UUsxyUelElKnhNOlZ3RFAHMK/ivuZ6BJLTixuafV2AcjJBnKbAoU5gjNLDgZyHhgbL8uqJ6bMAtuMbLdXAIQyM/HD9Gh9e2HxLWQCzHSSvzI6m/tPJG/xV/Xmb2NmLUUqntaTyCoOrDmCso9de+lo5JKT85Vda6CAY+vpvQ+wRGHxmF5WobCHxXuux4Y9fPTDkWOnsxUTzyAwIDAQAB
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  #  log-path: /opt/whatsup-mall-plus/log   win E://whatsup-mall-plus//log
  log-path: /opt/whatsup-mall-plus/log
  signtype: RSA2
